version: "3"
services:
  edgedb:
    image: edgedb/edgedb
    env_file:
      - vars.env
    volumes:
      - "./dbschema:/dbschema"
      - "edgedb-data:/var/lib/edgedb/data"
    ports:
      - "5657:5657"

  piggy-bank:
    image: piggy-bank:latest
    env_file:
      - vars.env
    build:
      dockerfile: Dockerfile
      context: .
    restart: on-failure
    depends_on:
      - edgedb

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - "3000:3000"
    environment:
      - GF_PATHS_CONFIG=/etc/grafana/custom.ini
    volumes:
      - ./grafana/custom.ini:/etc/grafana/custom.ini
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/plugins:/var/lib/grafana/plugins
      - type: bind
        source: ./grafana/dashboard.json
        target: /var/lib/grafana/dashboards/avoid/avoid.json


volumes:
  edgedb-data: {}
