# Configuration file version
apiVersion: 1

# List of data sources to delete from the database.
deleteDatasources:
  - name: EdgeDB
    orgId: 1

# List of data sources to insert/update depending on what's
# available in the database.
datasources:
  # <string, required> Sets the name you use to refer to
  # the data source in panels and queries.
  - name: EdgeDB
    # <string, required> Sets the data source type.
    type: washed-edgedb-datasource
    # <string, required> Sets the access mode, either
    # proxy or direct (Server or Browser in the UI).
    # Some data sources are incompatible with any setting
    # but proxy (Server).
    access: proxy
    # <int> Sets the organization id. Defaults to orgId 1.
    orgId: 1
    # <string> Sets a custom UID to reference this
    # data source in other parts of the configuration.
    # If not specified, Grafana generates one.
    uid: abd1c33d-26a6-4c97-a86a-f4d3466403a7
    # <string> Sets the data source's URL, including the
    # port.
    jsonData:
      host: edgedb
      port: "5657"
      user: edgedb
      database: edgedb
      tlsMode: insecure
    secureJsonData:
      # <string> Sets the database password, if necessary.
      password:
    version: 1
    # <bool> Allows users to edit data sources from the
    # Grafana UI.
    editable: false
