{
 "title": "All-time expences",
 "time": { "from": "2023-02-03T02:32:08.926Z", "to": "2023-05-02T12:59:01.542Z" },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Panel Title",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "queryText": "SELECT Invoice { time := .date, value := .total };\nSELECT HandInvoice { time := .message.date, value := .total };"
    }
   ]
  },
  {
   "title": "Total",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT Invoice { time := .date, value := .total } filter .time >= to_datetime($__from / 1000) and .time <= to_datetime($__to / 1000);\nSELECT HandInvoice { time := .message.date, value := .total } filter .time >= to_datetime($__from / 1000) and .time <= to_datetime($__to / 1000);"
    }
   ]
  },
  {
   "title": "Current month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "with\n    current_month := datetime_current() - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'day')-1) ++ ' day')  - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'hour')) ++ ' hours'),\nSELECT Invoice { time := .date, value := .total } filter .time >= current_month;\nwith\n    current_month := datetime_current() - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'day')-1) ++ ' day')  - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'hour')) ++ ' hours'),\nSELECT HandInvoice { time := .message.date, value := .total } filter .time >= current_month;"
    }
   ]
  },
  {
   "title": "Previous month",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "with\n    current_month := datetime_current() - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'day')-1) ++ ' day')  - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'hour')) ++ ' hours'),\n    previous_month := current_month - <cal::relative_duration>('1 month')\nSELECT Invoice { time := .date, value := .total } filter .time >= previous_month and .time <= current_month;\nwith\n    current_month := datetime_current() - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'day')-1) ++ ' day')  - <cal::relative_duration>(<str>(datetime_get(datetime_current(), 'hour')) ++ ' hours'),\n    previous_month := current_month - <cal::relative_duration>('1 month')\nSELECT HandInvoice { time := .message.date, value := .total } filter .time >= previous_month and .time <= current_month;"
    }
   ]
  },
  {
   "title": "Total Slava",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT Invoice { time := .date, value := .total, user := .message.user.username } filter .time >= to_datetime($__from / 1000) and .time <= to_datetime($__to / 1000) and .user = 'Avoid_me';\nSELECT HandInvoice { time := .message.date, value := .total, user := .message.user.username } filter .time >= to_datetime($__from / 1000) and .time <= to_datetime($__to / 1000) and .user = 'Avoid_me';"
    }
   ]
  },
  {
   "title": "Total Mawa",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "queryText": "SELECT Invoice { time := .date, value := .total, user := .message.user.username } filter .time >= to_datetime($__from / 1000) and .time <= to_datetime($__to / 1000) and .user = 'vanessarish';\nSELECT HandInvoice { time := .message.date, value := .total, user := .message.user.username } filter .time >= to_datetime($__from / 1000) and .time <= to_datetime($__to / 1000) and .user = 'vanessarish';"
    }
   ]
  }
 ]
}